name: Schema Validation

on:
  pull_request:

jobs:
  validate-schema:
    name: schema-validator
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: "npm"

      - name: Install dependencies
        run: npm ci

      - name: Parse Markdown
        run: npm run parse-markdown

      - name: Verify Schema
        run: npm run validation:aip-schema
