name: Upload IPFS

on:
  pull_request:
    branches:
      - master

jobs:
  upload-to-ipfs:
    name: aip-uploader
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Rename aip to upper case
        run: cd content/aips && bash toUpper.sh || true && cd ../..

      - uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: "npm"

      - name: Install dependencies
        run: npm ci

      - name: Parse Markdown
        run: npm run parse-markdown

      - name: Upload to Pinata and theGraph IPFS
        env:
          PINATA_KEY: ${{ secrets.PINATA_KEY }}
          PINATA_SECRET: ${{ secrets.PINATA_SECRET }}
        run: npm run upload:pinata-thegraph

      - name: Update readme
        run: npm run ci:generate-readme

      - name: Commit changes
        run: |
          if [[ -z $(git status -s) ]]
          then
            echo "tree is clean"
          else
            git config --global user.name 'Cache bot'
            git config --global user.email 'cache-bot@users.noreply.github.com'
            git add .
            git commit -m "chore(cache): update ipfs aips :robot:"
            git push origin ${{ github.event.repository.default_branch }}
          exit
          fi
